# SPDX-License-Identifier: Apache-2.0
# https://megalinter.io/latest/supported-linters/
ENABLE_LINTERS:
  - ACTION_ZIZMOR
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - GO_GOLANGCI_LINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_BETTERLEAKS
  - YAML_YAMLLINT
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
